/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterIntakeRouteImport } from './routes/water-intake'
import { Route as WaistToHipRatioRouteImport } from './routes/waist-to-hip-ratio'
import { Route as TdeeRouteImport } from './routes/tdee'
import { Route as ProteinRouteImport } from './routes/protein'
import { Route as MacrosRouteImport } from './routes/macros'
import { Route as LeanBodyMassRouteImport } from './routes/lean-body-mass'
import { Route as CalorieDeficitRouteImport } from './routes/calorie-deficit'
import { Route as BodyFatRouteImport } from './routes/body-fat'
import { Route as BmrRouteImport } from './routes/bmr'
import { Route as IndexRouteImport } from './routes/index'

const WaterIntakeRoute = WaterIntakeRouteImport.update({
  id: '/water-intake',
  path: '/water-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const WaistToHipRatioRoute = WaistToHipRatioRouteImport.update({
  id: '/waist-to-hip-ratio',
  path: '/waist-to-hip-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const TdeeRoute = TdeeRouteImport.update({
  id: '/tdee',
  path: '/tdee',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteinRoute = ProteinRouteImport.update({
  id: '/protein',
  path: '/protein',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosRoute = MacrosRouteImport.update({
  id: '/macros',
  path: '/macros',
  getParentRoute: () => rootRouteImport,
} as any)
const LeanBodyMassRoute = LeanBodyMassRouteImport.update({
  id: '/lean-body-mass',
  path: '/lean-body-mass',
  getParentRoute: () => rootRouteImport,
} as any)
const CalorieDeficitRoute = CalorieDeficitRouteImport.update({
  id: '/calorie-deficit',
  path: '/calorie-deficit',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyFatRoute = BodyFatRouteImport.update({
  id: '/body-fat',
  path: '/body-fat',
  getParentRoute: () => rootRouteImport,
} as any)
const BmrRoute = BmrRouteImport.update({
  id: '/bmr',
  path: '/bmr',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bmr': typeof BmrRoute
  '/body-fat': typeof BodyFatRoute
  '/calorie-deficit': typeof CalorieDeficitRoute
  '/lean-body-mass': typeof LeanBodyMassRoute
  '/macros': typeof MacrosRoute
  '/protein': typeof ProteinRoute
  '/tdee': typeof TdeeRoute
  '/waist-to-hip-ratio': typeof WaistToHipRatioRoute
  '/water-intake': typeof WaterIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bmr': typeof BmrRoute
  '/body-fat': typeof BodyFatRoute
  '/calorie-deficit': typeof CalorieDeficitRoute
  '/lean-body-mass': typeof LeanBodyMassRoute
  '/macros': typeof MacrosRoute
  '/protein': typeof ProteinRoute
  '/tdee': typeof TdeeRoute
  '/waist-to-hip-ratio': typeof WaistToHipRatioRoute
  '/water-intake': typeof WaterIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bmr': typeof BmrRoute
  '/body-fat': typeof BodyFatRoute
  '/calorie-deficit': typeof CalorieDeficitRoute
  '/lean-body-mass': typeof LeanBodyMassRoute
  '/macros': typeof MacrosRoute
  '/protein': typeof ProteinRoute
  '/tdee': typeof TdeeRoute
  '/waist-to-hip-ratio': typeof WaistToHipRatioRoute
  '/water-intake': typeof WaterIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bmr'
    | '/body-fat'
    | '/calorie-deficit'
    | '/lean-body-mass'
    | '/macros'
    | '/protein'
    | '/tdee'
    | '/waist-to-hip-ratio'
    | '/water-intake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bmr'
    | '/body-fat'
    | '/calorie-deficit'
    | '/lean-body-mass'
    | '/macros'
    | '/protein'
    | '/tdee'
    | '/waist-to-hip-ratio'
    | '/water-intake'
  id:
    | '__root__'
    | '/'
    | '/bmr'
    | '/body-fat'
    | '/calorie-deficit'
    | '/lean-body-mass'
    | '/macros'
    | '/protein'
    | '/tdee'
    | '/waist-to-hip-ratio'
    | '/water-intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BmrRoute: typeof BmrRoute
  BodyFatRoute: typeof BodyFatRoute
  CalorieDeficitRoute: typeof CalorieDeficitRoute
  LeanBodyMassRoute: typeof LeanBodyMassRoute
  MacrosRoute: typeof MacrosRoute
  ProteinRoute: typeof ProteinRoute
  TdeeRoute: typeof TdeeRoute
  WaistToHipRatioRoute: typeof WaistToHipRatioRoute
  WaterIntakeRoute: typeof WaterIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-intake': {
      id: '/water-intake'
      path: '/water-intake'
      fullPath: '/water-intake'
      preLoaderRoute: typeof WaterIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waist-to-hip-ratio': {
      id: '/waist-to-hip-ratio'
      path: '/waist-to-hip-ratio'
      fullPath: '/waist-to-hip-ratio'
      preLoaderRoute: typeof WaistToHipRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tdee': {
      id: '/tdee'
      path: '/tdee'
      fullPath: '/tdee'
      preLoaderRoute: typeof TdeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protein': {
      id: '/protein'
      path: '/protein'
      fullPath: '/protein'
      preLoaderRoute: typeof ProteinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros': {
      id: '/macros'
      path: '/macros'
      fullPath: '/macros'
      preLoaderRoute: typeof MacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lean-body-mass': {
      id: '/lean-body-mass'
      path: '/lean-body-mass'
      fullPath: '/lean-body-mass'
      preLoaderRoute: typeof LeanBodyMassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calorie-deficit': {
      id: '/calorie-deficit'
      path: '/calorie-deficit'
      fullPath: '/calorie-deficit'
      preLoaderRoute: typeof CalorieDeficitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-fat': {
      id: '/body-fat'
      path: '/body-fat'
      fullPath: '/body-fat'
      preLoaderRoute: typeof BodyFatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmr': {
      id: '/bmr'
      path: '/bmr'
      fullPath: '/bmr'
      preLoaderRoute: typeof BmrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BmrRoute: BmrRoute,
  BodyFatRoute: BodyFatRoute,
  CalorieDeficitRoute: CalorieDeficitRoute,
  LeanBodyMassRoute: LeanBodyMassRoute,
  MacrosRoute: MacrosRoute,
  ProteinRoute: ProteinRoute,
  TdeeRoute: TdeeRoute,
  WaistToHipRatioRoute: WaistToHipRatioRoute,
  WaterIntakeRoute: WaterIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
